log:
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

positions:
  list:
    - Back-end
    - Front-end
    - Manager
    - DevOps
    - QA
    - Solidity
    - Designer
    - other

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: identity-svc
  service_port: 80
