on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run code review
        uses: reviewdog/action-golangci-lint@v2
        with:
          level: error
          fail_on_error: true
